plugins {
  id 'com.android.library'
  id 'expo-module-gradle-plugin'
}

import groovy.json.JsonSlurper

def packageJson = new JsonSlurper().parseText(file('../package.json').text)

group = 'expo.modules.tailscalecheck'
version = packageJson.version

android {
  namespace "expo.modules.tailscalecheck"
  defaultConfig {
    versionCode 1
    versionName packageJson.version
  }
  lintOptions {
    abortOnError false
  }
}
